---
name: Draft Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update-release-draft:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Run release drafter
        uses: release-drafter/release-drafter@v6.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
