---
name: Sync labels

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/labels.yml

jobs:
  labels:
    name: Sync labels
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Run Label Syncer
        uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
